### ISSUE TITLE
Error ENOENT with meteor build cordova.

### ISSUE THREAD

**Issue by sqrdcat** [asteroid-devs/assignly#1]
Cordova log : 

/home/sqrdcat/.meteor/packages/meteor-tool/.1.0.45.t9p8sg++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/fibers/future.js:278
                        throw(ex);
                              ^
Error: ENOENT, readdir '/home/sqrdcat/Documents/METEOR/assignr/.meteor/local/cordova-build/platforms/android/ant-build'
    at Object.Future.wait (/home/sqrdcat/.meteor/packages/meteor-tool/.1.0.45.t9p8sg++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at Object.wrapper (/home/sqrdcat/.meteor/packages/meteor-tool/.1.0.45.t9p8sg++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/files.js:1330:24)
    at findApkPath (/home/sqrdcat/.meteor/packages/meteor-tool/.1.0.45.t9p8sg++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/commands.js:956:30)
    at /home/sqrdcat/.meteor/packages/meteor-tool/.1.0.45.t9p8sg++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/commands.js:941:21
    at Array.forEach (native)
    at Function._.each._.forEach (/home/sqrdcat/.meteor/packages/meteor-tool/.1.0.45.t9p8sg++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at buildCommand (/home/sqrdcat/.meteor/packages/meteor-tool/.1.0.45.t9p8sg++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/commands.js:924:29)
    at Command.main.registerCommand._.extend.name [as func] (/home/sqrdcat/.meteor/packages/meteor-tool/.1.0.45.t9p8sg++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/commands.js:738:12)
    at /home/sqrdcat/.meteor/packages/meteor-tool/.1.0.45.t9p8sg++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/main.js:1345:23

**Comment by sqrdcat** [comment]
Tested again on other machine. Same result.
